name: 'actions-autify-light'
description: 'Simple GitHub Actions for Autify'
inputs:
  project_id:
    description: 'Autify Project ID'
    required: true
  testplan_id:
    description: 'Autify Testplan ID'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project_id }}
    - ${{ inputs.testplan_id }}
  env:
    AUTIFY_PERSONAL_TOKEN: ${{ secrets.AUTIFY_PERSONAL_TOKEN }}
