name: Test
on: pull_request

jobs:
  running-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: With
        uses: ./
        with:
          project_id: ${{ secrets.AUTIFY_PROJECT_ID }}
          testplan_id: ${{ secrets.AUTIFY_TESTPLAN_ID }}
