name: Test
on: pull_request

jobs:
  running-test:
    runs-on: ubuntu-latest
    environment:
      name: CI
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run
        uses: ./
        with:
          project_id: 391
          testplan_id: 32135
        env:
          AUTIFY_PERSONAL_TOKEN: ${{ secrets.AUTIFY_PERSONAL_TOKEN }}
