name: Test
on: pull_request

jobs:
  running-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run
        uses: ./
        with:
          project_id: ${{ secrets.AUTIFY_PROJECT_ID }}
          testplan_id: ${{ secrets.AUTIFY_TESTPLAN_ID }}
          personal_token: ${{ secrets.AUTIFY_PERSONAL_TOKEN }}
